### ISSUE TITLE
Theming Support

### ISSUE THREAD

**Issue by cengels** [cengels/skywriter#2]
## Description

Support for custom user themes. These themes concern the look of the **main text area only** and are not used to style the general UI. Styling possibilities include paragraph spacing, indentation, background and font colors, font size and family, as well as adjusting the individual formatting styles (bold, italic, headings 1-6, ...).

## Task List

- [x] Add a new preferences page tab for themes (or its own menu entry)
- [x] Link these new preferences with a configuration element
- [x] Serialization/deserialization and storage of themes on the disk
- [x] Fully featured theme editor with preview of changes
- [x] Overall menu styling
